FROM nginx:alpine

## Not allowed in OpenShift EXPOSE 80 - the line below is just documentation 

EXPOSE 8080

COPY bin/build /usr/share/nginx/html

COPY bin/default.conf.template /etc/nginx/templates/default.conf.template