kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airbyte-admin-binding
  namespace: a1b9b0-dev
subjects:
  - kind: ServiceAccount
    name: airbyte-admin
    namespace: a1b9b0-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airbyte-admin-role
