kind: ServiceAccount
apiVersion: v1
metadata:
  name: airbyte-admin
secrets:
  - name: airbyte-admin-dockercfg-44fzb
  - name: airbyte-admin-token-q222h
imagePullSecrets:
  - name: airbyte-admin-dockercfg-44fzb
